live_config_reload = true

[window]
opacity = 0.85
startup_mode = "Maximized"

[font]
size = 14
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow"},
]
