live_config_reload = true

[window]
#opacity = 0.85
#startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Fullscreen" 

[font]
size = 14
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow"},
]
